```{r}
library(knitr)
library(pander)
```

# read chunk (does not run code)
```{r echo=FALSE}
read_chunk('rMDtest.R')
```

# run the variablesXY chunk and use the variables it creates
```{r first}
<<variablesXY>>
  head(data.frame(x,y))

```

# run the plotXY chunk and create the plot
```{r second}
<<plotXY>>
```

```{r}
Pandoc.brew(text = "# Demonstrating a conditional
<% for (i in 1:5) { %>
## This is a header for <%=i%>
<% if (i == 3) { %>
Hey, that's **almost** <%=pi%>, that's between <%=3:4%>! Wanna fit a model to _celebrate_?
<%= lm(mpg ~ hp, mtcars) %>
<% }} %>")
```

```{r, message=FALSE, warning=FALSE, results='asis', tidy=TRUE}
for (i in 1:3) {
  pander(Pandoc.brew(text = "# Demonstrating a nice loop
  ## This is a header for <%=i%>
  "))
  plot(1:10)
}

```

```{r}
plot(1:10)
pander("headign")
pander(Pandoc.brew(text = "# Demonstrating a nice loop
<% for (i in 1:5) { %>
## This is a header for <%=i%>
#' This is a comment for <%=i%>
<% plot(23) %>
<% } %>"))
plot(1:10)
```

```{r echo=TRUE}
for(i in 1:3) {
    pander(cat(i))
    plot(i)
}
```

```{r car_sum, results='asis'}
  for (i in 1:3) {
    library(pander)
    car_summary<-summary(cars)
    pander(print(pander(car_summary, caption = "This is a summary of cars")))
  }
```

Tables
======
 
```{r table1, comment=NA, results='asis'}
library(xtable)
data(iris)
print(xtable(head(iris, 10)), type = "html", include.rownames = F)
```

Tester
===== 

```{r,results='asis', echo=FALSE}
for (i in 1:3) {
rd <- sample(x=1e6:1e7, size = 10, replace = FALSE)
cat(rd, sep = "\n")
plot(1:10)
}
```

```{r}
for (i in 1:3) {
# cat(c('test', 'test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7'), sep = "\n")
plot(1:10)
}
```












## This is it!!!


```{r, results='asis'}
for(i in 1:3) {
    cat(c('test', 'test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7'), sep = "\n")
    cat(c(''), sep="\n\n\n")
    
    
    
    
    
    
    print(knitr::kable(mtcars))
#     plot(i:10)
    cat(c(''), sep="\n\n\n")
}
```













```{r,results='asis'}
for (n in rd) {
cat(paste0(n, '\\newline \n')) } 
```

```{r,results='hold', echo=FALSE}
print("<div class='red2'>")
rd <- sample(x=1e6:1e7, size = 10, replace = FALSE)
cat(rd, sep = "\n")
print("</div>")
```